### ISSUE TITLE
[PE-D][Tester A] Lessons at odd hours should not be allowed

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103-F11-2/tp#295]
Lesson at 01:01 - 02:01 is allowed, which i dont think should be allowed because nobody does 1am classes anyways. 
![Screenshot 2024-11-08 at 5.23.58 PM.png](https://raw.githubusercontent.com/Al-ez/ped/main/files/561b8149-8d87-4ed8-b4d7-4265b69adcae.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: Al-ez/ped#15

**Comment by Chronoxy** [comment]
Just because u dont do it doesnt mean nobody does it
